image:
  tag: 8.5.0

replicas: 1

imageRenderer:
  enabled: false

grafana.ini:
  server:
    root_url: https://monitor.linagora.com.vn
    enable_gzip: "true"
  auth:
    disable_login_form: "false"
  unified_alerting:
    enabled: "true"
  dataproxy:
    timeout: 600s
    tls_handshake_timeout_seconds: 600s

persistence:
  type: pvc
  enabled: true
  storageClassName: csi-sc-cinderplugin-ssd
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
  hosts:
    - monitor.linagora.com.vn
  tls:
    - secretName: monitor-ingress-tls
      hosts:
      - monitor.linagora.com.vn

#Default Admin - Hidden by default
admin:
  existingSecret: grafana-secrets
  userKey: defaultAdmin
  passwordKey: defaultPassword

extraSecretMounts:
  - name: grafana-secrets
    secretName: grafana-secrets
    mountPath: /etc/secrets/
    defaultMode: 0440
    readOnly: true

testFramework:
  enabled: false
